default: cpsc2150/extendedConnectX/AbsGameBoard.java cpsc2150/extendedConnectX/BoardPosition.java cpsc2150/extendedConnectX/GameBoard.java cpsc2150/extendedConnectX/GameScreen.java cpsc2150/extendedConnectX/IGameBoard.java
	javac cpsc2150/extendedConnectX/AbsGameBoard.java cpsc2150/extendedConnectX/BoardPosition.java cpsc2150/extendedConnectX/GameBoard.java cpsc2150/extendedConnectX/GameScreen.java cpsc2150/extendedConnectX/IGameBoard.java

run: cpsc2150/extendedConnectX/GameScreen.class cpsc2150/extendedConnectX/BoardPosition.class cpsc2150/extendedConnectX/GameBoard.class
	java cpsc2150.extendedConnectX.GameScreen

clean:
	rm -f cpsc2150/extendedConnectX/*.class