default: cpsc2150/extendedConnectX/BoardPosition.java cpsc2150/extendedConnectX/GameBoard.java cpsc2150/extendedConnectX/GameScreen.java cpsc2150/extendedConnectX/IGameBoard.java cpsc2150/extendedConnectX/GameBoard.java cpsc2150/extendedConnectX/AbsGameBoard.java
	javac cpsc2150/extendedConnectX/BoardPosition.java cpsc2150/extendedConnectX/GameBoard.java cpsc2150/extendedConnectX/GameScreen.java cpsc2150/extendedConnectX/IGameBoard.java cpsc2150/extendedConnectX/GameBoard.java cpsc2150/extendedConnectX/AbsGameBoard.java

run: cpsc2150/extendedConnectX/BoardPosition.java cpsc2150/extendedConnectX/GameBoard.java cpsc2150/extendedConnectX/GameScreen.java cpsc2150/extendedConnectX/IGameBoard.java cpsc2150/extendedConnectX/GameBoard.java cpsc2150/extendedConnectX/AbsGameBoard.java
	java cpsc2150/extendedConnectX/GameScreen
clean:
	rm cpsc2150/extendedConnectX/*.class
