default: cpsc2150/MyDeque/*.java
	javac -Xlint:unchecked cpsc2150/MyDeque/*.java
runChar: cpsc2150/MyDeque/*.class
	java cpsc2150.MyDeque.DequeApp
runInt: cpsc2150/MyDeque/*.class
	java cpsc2150.MyDeque.IntegerDequeApp
clean:
	rm -f cpsc2150/MyDeque/*.class
