default: cpsc2150/banking/models cpsc2150/banking/models cpsc2150/banking/models cpsc2150/banking/models cpsc2150/banking/models cpsc2150/banking/models cpsc2150/banking/models cpsc2150/banking/controllers cpsc2150/banking/controllers cpsc2150/banking/views cpsc2150/banking/views
	javac cpsc2150/banking/MortgageApp.java cpsc2150/banking/models/IMortgage.java cpsc2150/banking/models/ICustomer.java cpsc2150/banking/models/AbsMortgage.java cpsc2150/banking/models/AbsCustomer.java cpsc2150/banking/models/Mortgage.java cpsc2150/banking/models/Customer.java cpsc2150/banking/controllers/IMortgageController.java cpsc2150/banking/controllers/MortgageController.java cpsc2150/banking/views/IMortgageView.java cpsc2150/banking/views/MortgageView.java
run: cpsc2150/banking/models cpsc2150/banking/models cpsc2150/banking/models cpsc2150/banking/models cpsc2150/banking/models cpsc2150/banking/models cpsc2150/banking/models
	java cpsc2150.banking.MortgageApp
clean:
	rm -f cpsc2150/banking/models/*.class
	rm -f cpsc2150/banking/*.class
